server:
  port: 8080
spring:
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password: password
  jackson.default-property-inclusion: NON_NULL
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false