---
openapi: '3.0.3'
info:
  title: Prices API challenge
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /product/{productId}/price:
    get:
      operationId: findPrice
      summary: Finds for a product price in a concrete date
      parameters:
        - $ref: '#/components/parameters/ProductId'
        - $ref: '#/components/parameters/BrandId'
        - $ref: '#/components/parameters/Date'
      responses:
        200:
          description: Price found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Price'
        404:
          description: Price not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
security:
  - BasicAuth: [ ]
components:
  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
  parameters:
    ProductId:
      name: productId
      in: path
      required: true
      description: Identifier of the product
      schema:
        type: integer
        format: int64
    BrandId:
      name: brandId
      in: query
      required: true
      description: Identifier of the brand
      schema:
        type: number
        minimum: 1
    Date:
      name: date
      in: query
      required: true
      description: Date of the product price we are searching for
      schema:
        type: string
        format: date-time
  schemas:
    Price:
      type: object
      required:
        - productId
        - brandId
        - price
        - currency
        - startDate
        - endDate
      properties:
        productId:
          type: integer
          format: int64
          minimum: 1
        brandId:
          type: integer
          format: int32
          minimum: 1
        price:
          type: number
          format: float
          minimum: 0
        currency:
          type: string
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: string
        message:
          type: string
